max_episodes: 10000

log_interval: 10

save_interval: 100

set_reproducible: false


policy_model {
    type_: AntennaTopologyPolicyModel
    hidden_size: 64
    temperature: null
    tanh_constant: 1.5
}

surrogate_model {
    type_: EMResnet
    layers: [2,2,2]
    in_channels: 1
    out_dim: 1200
    load_from: surrogate_output/01/best_checkpoint.pt
}

rl {
    batch_size: 32
    entropy_coef: 0.001
    adv_eps: 1e-8
    grad_clip_norm: null
}

infer {
    n_samples: 100
    batch_size: 100
    top_k: 10
}

reward {
    type_: BandThresholdReward
    bands: [5.0, 6.0]
    threshold: 0.1
    weight: 1.0
    freq_start_ghz: 0.1
    freq_end_ghz: 29.6
    num_points: 60
    penalty_power: 2.0
    satisfied_bonus: 1.0
    clamp_s: false
}

optimizer {
    type_: AdamW
    lr: 0.0001
    betas: [0.9, 0.95]
    eps: 1e-8
    weight_decay: 1e-5
}

scheduler {
    type_: CosineAnnealingLR
    T_max: ${max_episodes}
    eta_min: 0.0001
}
