max_epochs: 200

log_interval: 10

only_evaluate: false

set_reproducible: false


data {
    type_: EMParquetDataloader

    x_key: topology_top_flat
    y_key: s11_mag

    x_enable_scale_to_minus1_1: true
    x_enable_unsqueeze_channel: true
    y_enable_frequency_crop: false
    y_original_start_freq: 0.1
    y_original_end_freq: 29.6
    y_original_num_points: 60
    y_crop_start_freq: null
    y_crop_end_freq: null
    y_enable_stat_normalize: false
    y_normalize_mean: 0.0
    y_normalize_max: 1.0
    y_normalize_min: 0.0

    s_curve_downsample_factor: 1

    root: ./data
    batch_size: 32
    num_workers: 4
    config: null
    train_filename: train_s2p.parquet
    val_filename: val_s2p.parquet
    pin_memory: true
    persistent_workers: false
    drop_last: true
}

model {
    type_: EMResnet
    layers: [2,2,2]
    in_channels: 1
    out_dim: 60
}

optimizer {
    type_: AdamW
    lr: 0.001
    betas: [0.9, 0.95]
    eps: 1e-8
    weight_decay: 1e-5
}

scheduler {
    type_: CosineAnnealingLR
    T_max: ${max_epochs}
    eta_min: 0.00001
}

loss {
    type_: L1Loss
}
